config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             path_names: {:sign_in => 'login', :sign_out => 'logout', :sign_up => 'register'}

  root 'static_pages#home'

  get '/faq', to: 'static_pages#faq', as: :faq
  get '/health', to: 'health#show'

  draw(:admin)

  resources :posts, path: :blog
  resources :users, only: [:show]

  get "/profile", to: "users#show", as: :profile
  get "/profile/edit", to: "users#edit", as: :edit_profile
  patch "/profile/edit", to: "users#update"
  post "/profile/password", to: "users#password", as: :update_password
  post "/profile/disavow",  to: "users#disavow", as: :disavow
  post "/profile/cancel_email_change", to: "users#cancel_email_change", as: :cancel_email_change
  post "/profile/resend_confirmation_email", to: "users#resend_confirmation_email", as: :resend_confirmation_email

  get "/contacts", to: "contacts#new"
  post "/contacts", to: "contacts#create"


  %w(404 422 500).each do |code|
    get code, to: 'errors#show', code: code
  end

  get "/*path", to: 'static_pages#page'

end

app/views/layouts/admin/_footer.html.slim
footer#footer.footer
  .copyright
    ' Built with
    strong
      a href="https://railsblueprint.com" target="_blank"
        | Rails Blueprint
  a.back-to-top data-controller="back-to-top" data-action="scroll@window->back-to-top#refresh click->back-to-top#click"
    i.bi.bi-arrow-up-short

app/views/layouts/admin/_header.html.slim
nav.navbar.navbar-dark.navbar-expand-xl.fixed-top.header
  .d-flex.align-items-center.justify-content-center.logo-area
    button.navbar-toggler aria-label="Toggle navigation" data-controller="sidebar" data-action="click->sidebar#show"
      span.navbar-toggler-icon
    = link_to "/admin", class: "logo d-none align-items-center justify-content-center d-xl-flex" do
      = inline_svg_tag "admin/logo_no_border_no_color.svg"
      span.d-none.d-sm-block
        = t("platform.name")
  = link_to "/admin", class: "logo d-flex align-items-center justify-content-center d-xl-none d-xxl-none" do
    = inline_svg_tag "admin/logo_no_border_no_color.svg"
    span.d-none.d-sm-block
      = t("platform.name")
  .search-bar
    form.search-form.d-flex.align-items-center action="/admin/search"
      input type="text" name="q" placeholder="Search" title="Enter search keyword"
      button type="submit" title="Search"
        i.bi.bi-search
  nav.header-nav.end-icons
    ul.d-flex.align-items-center
      li.nav-item.d-block.pe-3
        a.nav-link.nav-icon.search-bar-toggle data-controller="admin--search-bar" data-action="click->admin--search-bar#toggle" href="javascript:void(0)"
          i.bi.bi-search
      li.nav-item.dropdown
        = render partial: "layouts/admin/user_menu"
.search-bar-expandable
  form.search-form.d-flex.align-items-center action="/admin/search"
    input type="text" name="q" placeholder="Search" title="Enter search keyword"
    button type="submit" title="Search"
      i.bi.bi-search

app/views/layouts/admin/_sidebar.html.slim
aside#sidebar.sidebar
  .open-handle data-controller="sidebar" data-action="click->sidebar#hide"
    = bi "caret-left-fill"
  .sidebar-wrapper
    ul#sidebar-nav.sidebar-nav data-turbo-keep-scroll=true
      li.nav-item
        = active_link_to [:admin, :root], class: "nav-link nav-link-main", active: :exclusive do
          i.bi.bi-grid
          span = t('admin.nav.dashboard')
      - if policy(User).index?
        li.nav-item
          = active_link_to [:admin, :users], class: "nav-link nav-link-main" do
            i.bi.bi-people-fill
            span = t('admin.nav.users')
      - if policy(Post).index?
        li.nav-item
          = active_link_to [:admin, :posts], class: "nav-link nav-link-main" do
            i.bi.bi-newspaper
            span = t('admin.nav.posts')
      - if policy(Page).index?
        li.nav-item
          = active_link_to [:admin, :pages], class: "nav-link nav-link-main" do
            i.bi.bi-file
            span = t('admin.nav.pages')
      - if policy(Setting).index? || policy(MailTemplate).index?
        li.nav-item
          a.nav-link.nav-group.collapsed[data-bs-target="#configuration-nav" data-bs-toggle="collapse" href="#"]
            i.bi.bi-gear
            span
              = t('admin.nav.configuration')
            i.bi.bi-chevron-down.ms-auto
          ul#configuration-nav class="nav-content collapse #{class_names(show: config?)}" data-bs-parent="#sidebar-nav"
            - if policy(Setting).index?
              li
                = active_link_to [:admin, :settings], class: "nav-link" do
                  i.bi.bi-circle
                  span
                    = t('admin.nav.settings')
            - if policy(MailTemplate).index?
              li
                = active_link_to [:admin, :mail_templates], class: "nav-link" do
                  i.bi.bi-circle
                  span
                    = t('admin.nav.mail_templates')
      - if current_user.superadmin?
        li.nav-item
          a.nav-link.nav-group.collapsed[data-bs-target="#maintenance-nav" data-bs-toggle="collapse" href="#"]
            i.bi.bi-wrench
            span
              = t('admin.nav.maintenance')
            i.bi.bi-chevron-down.ms-auto
          ul#maintenance-nav class="nav-content collapse #{class_names(show: maintenance?)}" data-bs-parent="#sidebar-nav"
            li
              = nav_link [:admin, :pg_hero] do
                i.bi.bi-circle
                span
                  = t('admin.nav.pg_hero')
            li
              = nav_link [:admin, :good_job] do
                i.bi.bi-circle
                span
                  = t('admin.nav.good_job')
      - unless AppConfig.hide_demo_elements
        li.nav-heading
          = t('admin.nav.design_system.design_system')
        li.nav-item
          = nav_link admin_design_system_colors_path do
            i.bi.bi-palette
            span
              = t('admin.nav.design_system.color_system')
          a.nav-link.nav-group data-bs-target="#components-nav" data-bs-toggle="collapse" href="#" class=class_names(collapsed: !components?)
            i.bi.bi-menu-button-wide
            span
              = t('admin.nav.components')
            i.bi.bi-chevron-down.ms-auto
          ul#components-nav class="nav-content collapse #{class_names(show: components?)}" data-bs-parent="#sidebar-nav"
            li
              = nav_link admin_design_system_components_alerts_path do
                i.bi.bi-circle
                span
                  = t('admin.nav.design_system.alerts')
            li
              = nav_link admin_design_system_components_accordion_path do
                i.bi.bi-circle
                span
                  = t('admin.nav.design_system.accordion')
            li
              = nav_link admin_design_system_components_badges_path do
                i.bi.bi-circle
                span
                  = t('admin.nav.design_system.badges')
            li
              = nav_link admin_design_system_components_breadcrumbs_path do
                i.bi.bi-circle
                span
                  = t('admin.nav.design_system.breadcrumbs')
            li
              = nav_link admin_design_system_components_buttons_path do
                i.bi.bi-circle
                span
                  = t('admin.nav.design_system.buttons')
            li
              = nav_link admin_design_system_components_cards_path do
                i.bi.bi-circle
                span
                  = t('admin.nav.design_system.cards')
            li
              = nav_link admin_design_system_components_carousel_path do
                i.bi.bi-circle
                span
                  = t('admin.nav.design_system.carousel')
            li
              = nav_link admin_design_system_components_list_group_path do
                i.bi.bi-circle
                span
                  = t('admin.nav.design_system.list_group')
            li
              = nav_link admin_design_system_components_modal_path do
                i.bi.bi-circle
                span
                  = t('admin.nav.design_system.modal')
            li
              = nav_link admin_design_system_components_tabs_path do
                i.bi.bi-circle
                span
                  = t('admin.nav.design_system.tabs')
            li
              = nav_link admin_design_system_components_pagination_path do
                i.bi.bi-circle
                span
                  = t('admin.nav.design_system.pagination')
            li
              = nav_link admin_design_system_components_progress_path do
                i.bi.bi-circle
                span
                  = t('admin.nav.design_system.progress')
            li
              = nav_link admin_design_system_components_spinners_path do
                i.bi.bi-circle
                span
                  = t('admin.nav.design_system.spinners')
            li
              = nav_link admin_design_system_components_toasts_path do
                i.bi.bi-circle
                span
                  = t('admin.nav.design_system.toasts')
            li
              = nav_link admin_design_system_components_tooltips_path do
                i.bi.bi-circle
                span
                  = t('admin.nav.design_system.tooltips')
        li.nav-item
          a.nav-link.nav-group data-bs-target="#forms-nav" data-bs-toggle="collapse" href="#" class=class_names(collapsed: !forms?)
            i.bi.bi-journal-text
            span
              = t('admin.nav.design_system.forms')
            i.bi.bi-chevron-down.ms-auto
          ul id="forms-nav" class="nav-content collapse #{class_names(show: forms?)}" data-bs-parent="#sidebar-nav"
            li
              = nav_link admin_design_system_forms_elements_path do
                i.bi.bi-circle
                span
                  = t('admin.nav.design_system.form_elements')
            li
              = nav_link admin_design_system_forms_layouts_path do
                i.bi.bi-circle
                span
                  = t('admin.nav.design_system.form_layouts')
            li
              = nav_link admin_design_system_forms_editors_path do
                i.bi.bi-circle
                span
                  = t('admin.nav.design_system.form_editors')
            li
              = nav_link admin_design_system_forms_validation_path do
                i.bi.bi-circle
                span
                  = t('admin.nav.design_system.form_validation')
        li.nav-item
          a.nav-link.nav-group data-bs-target="#tables-nav" data-bs-toggle="collapse" href="#" class=class_names(collapsed: !tables?)
            i.bi.bi-layout-text-window-reverse
            span
              = t('admin.nav.design_system.tables')
            i.bi.bi-chevron-down.ms-auto
          ul id="tables-nav" class="nav-content collapse #{class_names(show: tables?)}" data-bs-parent="#sidebar-nav"
            li
              = nav_link admin_design_system_tables_general_path do
                i.bi.bi-circle
                span
                  = t('admin.nav.design_system.tables_general')
            li
              = nav_link admin_design_system_tables_data_path do
                i.bi.bi-circle
                span
                  = t('admin.nav.design_system.tables_data')
        li.nav-item
          a.nav-link.nav-group data-bs-target="#charts-nav" data-bs-toggle="collapse" href="#" class=class_names(collapsed: !charts?)
            i.bi.bi-bar-chart
            span
              = t('admin.nav.design_system.charts')
            i.bi.bi-chevron-down.ms-auto
          ul id="charts-nav" class="nav-content collapse #{class_names(show: charts?)}" data-bs-parent="#sidebar-nav"
            li
              = nav_link admin_design_system_charts_chartjs_path do
                i.bi.bi-circle
                span
                  = t('admin.nav.design_system.chartjs')
            li
              = nav_link admin_design_system_charts_apexcharts_path do
                i.bi.bi-circle
                span
                  = t('admin.nav.design_system.apexcharts')
            li
              = nav_link admin_design_system_charts_echarts_path do
                i.bi.bi-circle
                span
                  = t('admin.nav.design_system.echarts')
        li.nav-item
          a.nav-link.nav-group data-bs-target="#icons-nav" data-bs-toggle="collapse" href="#"  class=class_names(collapsed: !icons?)
            i.bi.bi-gem
            span
              = t('admin.nav.design_system.icons')
            i.bi.bi-chevron-down.ms-auto
          ul id="icons-nav" class="nav-content collapse #{class_names(show: icons?)}" data-bs-parent="#sidebar-nav"
            li
              = nav_link admin_design_system_icons_bootstrap_path do
                i.bi.bi-circle
                span
                  = t('admin.nav.design_system.bootstrap')
            li
              = nav_link admin_design_system_icons_fontawesome_path do
                i.bi.bi-circle
                span
                  = t('admin.nav.design_system.fontawesome')
            li
              = nav_link admin_design_system_icons_boxicons_path do
                i.bi.bi-circle
                span
                  = t('admin.nav.design_system.boxicons')
            li
              = nav_link admin_design_system_icons_remix_path do
                i.bi.bi-circle
                span
                  = t('admin.nav.design_system.remix')

app/views/layouts/admin/_user_menu.html.slim
a.nav-link.nav-profile.d-flex.align-items-center.pe-0.ps-2 href="#" data-bs-toggle="dropdown"
  .profile-image.icon.d-md-none
    .rounded-circle.circle-border.m-auto class="color-#{current_user.avatar_color}"
      span = current_user.initials
  span.d-none.d-md-block.dropdown-toggle
    = current_user.short_name
ul.dropdown-menu.dropdown-menu-end.dropdown-menu-arrow.profile
  li.dropdown-header
    .profile-image
      .rounded-circle.circle-border.mb-3.m-auto class="color-#{current_user.avatar_color}"
        span = current_user.initials
    h6
      = current_user.short_name
    span
      = current_user.job
  li
    hr.dropdown-divider
  - if current_user.has_role?(:admin)
    li
      = link_to "/admin", class: "dropdown-item d-flex align-items-center" do
        i.bi.bi-briefcase
        span = t("admin.nav.admin")
    li
      hr.dropdown-divider
  = link_to profile_path, class: "dropdown-item d-flex align-items-center" do
    i.bi.bi-person
    span = t('actions.my_profile')
  li
    hr.dropdown-divider
  li
    = link_to faq_path, class: "dropdown-item d-flex align-items-center" do
      i.bi.bi-question-circle
      span = t('actions.need_help_q')
  li
    hr.dropdown-divider
  li
    = link_to destroy_user_session_path, class: "dropdown-item d-flex align-items-center", "data-turbo-method": "DELETE" do
      i.bi.bi-box-arrow-right
      span = t('actions.sign_out')